# default balance of 10,000 ether to simplify testing of ETH pools
networks:
  development:
    cmd_settings:
      default_balance: 10000
  network:

# exclude non-core contracts from coverage analysis
reports:
  exclude_paths:
    - contracts/testing/*.*
    - contracts/gauges/*.*

dependencies:
  - curvefi/curve-dao-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.4.2

hypothesis:
  phases:
    explicit: true
    reuse: false
    generate: true
    target: false
    shrink: false

autofetch_sources: true

compiler:
  solc:
    version:
    remappings:
      - "@openzeppelin=Openzeppelin/openzeppelin-contracts@4.4.2"
